name: Create Release Branch

#on:
#  workflow_dispatch:  # 手动触发
on:
  push:
    branches:
      - eva-zenni-patch-1
      
      
jobs:
  create_release_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout develop branch
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "mengyuan.zhu@zennioptical.com"

    - name: Push to repository
#      env:
#        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        release_branch="release-$(date +'%Y%m%d')"
        git checkout -b $release_branch
        git push
        
        
